name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Pull submodules
        run: git submodule update --init
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.1
        id: install-boost
        with:
          boost_version: 1.81.0
          platform_version: 18.04
          toolset: gcc
          arch: x86
      - name: Configure CMake in a 'build' subdirectory.
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}


      - name: Build project
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build

      - name: Run tests
        #working-directory: ${{github.workspace}}/bin
        run: ./bin/unit_test
