name: CarbonChat CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download and install Boost
      uses: MarkusJx/install-boost@v2.4.3
      with:
        boost_version: "1.81.0"
        boost_install_dir: C:\local
        platform_version: 2022
        toolset: msvc

